FROM python:3.6-alpine
RUN apk update && apk add --no-cache gcc musl-dev libffi-dev
COPY requirements.txt /src/
WORKDIR /src/
RUN pip install -r requirements.txt
ARG BASE_VERSION
ENV BASE_VERSION=$BASE_VERSION