apiVersion: v1
kind: Service
metadata:
  name: {{ include "address.fullname" . }}{{ .Values.environment }}
  labels:
    {{- include "address.labels" . | nindent 4 }}{{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "address.selectorLabels" . | nindent 4 }}{{ .Values.environment }}
